### create jobs
POST http://localhost:3000/jobs
Content-Type: application/json

{
    "title": "Example123311113",
    "queueName": "testdemo001"
}

### create Error jobs
POST http://localhost:3000/jobs/error
Content-Type: application/json

{
}

### create new queue
POST http://localhost:3000/queues
Content-Type: application/json

{
    "queueName": "testdemo001"
}

### Delete Queue
DELETE http://localhost:3000/queues
Content-Type: application/json

{
    "queueName": "testdemo001"
}

### create new worker
POST http://localhost:3000/worker
Content-Type: application/json

{
    "queueName": "testdemo001"
}
###