# how to create base64 string: https://www.obytes.com/blog/react-native-github-action
name: deploy to development server
on:
  push:
    branches:
      - develop
jobs:
  ssh-to-server-restart-service:
    needs:
      - test-unit
    name: restart-service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16']
    steps:
    - name: Check out Git repository # clone the repo to local ci workspace
      uses: actions/checkout@v2
    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    # - uses: "finnp/create-file-action@master"
    #   env:
    #     FILE_NAME: "./ssh-key-aha-dev.pem"
    #     FILE_DATA: ${{ secrets.SSH_KEY_AHA_DEV_VALUE }}
    - name: Create pem file
      run: echo "${{ secrets.SSH_KEY_AHA_DEV_VALUE }}" > ./ssh-key-aha-dev.pem
    - name: Create .env file
      run: echo "${{ secrets.DEV_ENV}}" > .env
    - name: Change file mode
      run: chmod 0600 ./ssh-key-aha-dev.pem
    - name: 'clear files on server'
      run: ssh -i ./ssh-key-aha-dev.pem  -o "StrictHostKeyChecking no" ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'rm -rf ./queue-core/**'
    - name: 'copy files to server'
      run: scp -i ./ssh-key-aha-dev.pem  -o "StrictHostKeyChecking no" -r ./**  ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/queue-core
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          cd ./queue-core
          npm install
          pm2 restart configs/ecosystem.dev.config.js
        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.SSH_KEY_AHA_DEV_VALUE }}
    # - name: 'copy files to server'
    #   run: ssh -i ./ssh-key-aha-dev.pem  -o "StrictHostKeyChecking no" ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd ./queue-core && ./scripts/pm2serverrestart.sh'
